/** English source keys keep fallback messages available without a locale bundle. */
export type WidgetBuiltinMessage =
  | "Only loaded rows are exported. Blank bounds include all loaded times."
  | "From (UTC seconds)"
  | "To (UTC seconds)"
  | "Study alignment"
  | "Source rows"
  | "Displayed rows"
  | "Use captured visible range"
  | "All loaded rows"
  | "Download CSV"
  | "Enter finite UTC seconds or leave the bound blank"
  | "The From bound must be before or equal to the To bound"
  | "Enable panning"
  | "Enable zooming"
  | "Go to"
  | "Go"
  | "Date"
  | "Range"
  | "From"
  | "To"
  | "Time"
  | "From time"
  | "To time"
  | "Showing {date}"
  | "Showing {from} to {to}"
  | "The range is wider than the chart. Showing {from} to {to}"
  | "History starts at {date}"
  | "The history limit stops at {date}"
  | "No older bars were found before {date}"
  | "Older history cannot load now. Showing from {date}"
  | "No bars at or after {date}"
  | "No bars between {from} and {to}"
  | "Go to needs a time-based interval"
  | "Enter a valid date"
  | "Could not load history: {error}"
  | "The end must not be before the start"
  | "Loading history"
  | "Times are in {zone}. A blank time is the start of the day, or its end for To."
  | "Dates are in {zone}."
  | "Charts"
  | "Chart {index}"
  | "Resize columns {first} and {second}"
  | "Resize rows {first} and {second}"
  | "Search"
  | "Enter a finite number"
  | "Minimum: {value}"
  | "Maximum: {value}"
  | "Use HHMM-HHMM with optional :days (1 to 7)"
  | "{label} (UTC seconds)"
  | "Symbol search is not configured; enter an instrument manually"
  | "Finish or cancel the active drawing before picking"
  | "This host cannot suspend the settings dialog"
  | "Choose an explicit pane and scale for this price input"
  | "Pick on chart"
  | "Pick {label} on the chart"
  | "Cancel pick"
  | "The value could not be picked"
  | "Add a study to the chart"
  | "Add level"
  | "Added {name}"
  | "Account"
  | "Accounts"
  | "Account: {name}"
  | "Analyzer"
  | "Available"
  | "Could not switch account: {error}"
  | "Equity"
  | "Loading account"
  | "Margin used"
  | "Stale"
  | "Alerts"
  | "Alerts are unavailable in this host"
  | "Alerts..."
  | "Armed"
  | "Auto-fit to the data"
  | "Fit primary prices only"
  | "Collapse indicator legends"
  | "Collapse pane"
  | "Expand pane"
  | "Move pane up"
  | "Move pane down"
  | "at the top"
  | "at the bottom"
  | "price pane stays on top"
  | "Price pane"
  | "Axis settings..."
  | "Bar close"
  | "Bar close evaluates confirmed values. Intrabar touch can fire on a wick that is absent from final history."
  | "Behind the series"
  | "Bring to front"
  | "Buy limit at {price}"
  | "Buy market"
  | "Buy stop at {price}"
  | "C"
  | "Cancel"
  | "Candle condition"
  | "Candle condition is unavailable"
  | "Capture"
  | "Capture chart"
  | "Chart alerts"
  | "Chart branding"
  | "Chart controls"
  | "Chart copied"
  | "Chart data download started"
  | "Chart header"
  | "Chart menu"
  | "Chart objects"
  | "Chart settings"
  | "Chart toolbar"
  | "Chart type"
  | "Claimed by {name}"
  | "Click for strong: every anchor lands on the nearest O/H/L/C"
  | "Click for weak: snaps when O/H/L/C is within a few pixels"
  | "Click to switch the magnet off"
  | "Close"
  | "Color"
  | "Compare with"
  | "Copy drawing"
  | "Copy failed: {error}"
  | "Copy image"
  | "Copy {count} drawings"
  | "Could not change lock for {name}"
  | "Could not change visibility for {name}"
  | "Could not focus {name}"
  | "Could not load"
  | "Could not load older history"
  | "Could not load {symbol} {interval}"
  | "Could not load {symbol} {interval}: {error}"
  | "Could not open settings for {name}"
  | "Could not remove {name}"
  | "Could not save this alert"
  | "Could not select {name}"
  | "Create alert"
  | "Create alert at {price}..."
  | "Create drawing alert..."
  | "Create study alert..."
  | "Cursor"
  | "Custom"
  | "Cut drawing"
  | "Cut {count} drawings"
  | "Dark"
  | "Dark theme"
  | "Data export failed: {error}"
  | "Default level"
  | "Defaults"
  | "Delete"
  | "Delete drawing"
  | "Delete {count} drawings"
  | "Disable"
  | "Disable {name}"
  | "Disabled"
  | "Dismiss"
  | "Done"
  | "Download PNG"
  | "Download SVG"
  | "Download chart data (CSV)"
  | "Draw"
  | "Drawing"
  | "Drawing actions"
  | "Drawing level is unavailable"
  | "Drawing text"
  | "Drawing tools"
  | "Duplicate"
  | "Edit"
  | "Edit alert"
  | "Edit levels..."
  | "Edit on chart"
  | "Edit text"
  | "Edit the expiry before enabling this alert"
  | "Enable"
  | "Enable {name}"
  | "Enabled"
  // Retained so existing host translation catalogs remain type compatible.
  | "Enter a valid expiry date and time in UTC"
  | "Enter an expiry date and time in UTC"
  | "Enter an expiry date and time"
  | "Every match"
  | "Expired"
  | "Expires {time}"
  | "Expires {time} UTC"
  | "Expires"
  | "Finish"
  | "Fit all bars"
  | "Focus"
  | "Focus {name}"
  | "H"
  | "Hidden"
  | "Hide"
  | "Hide drawing"
  | "Hide {name}"
  | "History is stale for {symbol} {interval}"
  | "History is stale for {symbol} {interval}. Reload to retry."
  | "History is stale. Refreshing {symbol} {interval}"
  | "History retention limit reached"
  | "In front of the series"
  | "Indicators"
  | "Indicators..."
  | "Input plot"
  | "Inputs"
  | "Interval"
  | "Interval {code}"
  | "Intrabar touch"
  | "Invert"
  | "Keep tool armed"
  | "Keyboard shortcuts"
  | "L"
  | "Label"
  | "Last fired {time}"
  | "Last fired {time} UTC"
  | "Level"
  | "Levels"
  | "Light"
  | "Light theme"
  | "Loading"
  | "Loading older history"
  | "Loading {symbol} {interval}"
  | "Lock"
  | "Lock drawing"
  | "Lock {name}"
  | "Locked"
  | "Magnet off"
  | "Magnet strong: every anchor lands on the nearest O/H/L/C"
  | "Magnet weak: snaps when O/H/L/C is within a few pixels"
  | "Magnet: {mode}"
  | "More"
  | "Move the scale closer to the plot"
  | "Move the scale further from the plot"
  | "Move the scale to the left"
  | "Move the scale to the right"
  | "No alerts. Create an alert for this chart."
  | "No bars for {symbol} {interval}"
  | "No data"
  | "No drawings to remove"
  | "No indicator on the chart to configure"
  | "No indicator to configure"
  | "No indicators are registered. Import the indicators tier to fill this list."
  | "No levels. Add one, or reset to the defaults."
  | "No match"
  | "No objects match your search."
  | "No objects on this chart."
  | "Nothing measured on this scale yet"
  | "Nothing to configure on this chart yet."
  | "Nothing to paste"
  | "O"
  | "OI"
  | "OK"
  | "Objects"
  | "Objects panel requires an object model"
  | "Off: one drawing per pick"
  | "On: the tool stays armed after each drawing"
  | "Once"
  | "One drawing per pick"
  | "Open interest is unavailable for this instrument."
  | "Order"
  | "Order entry is locked by the host"
  | "Order entry is locked during replay"
  | "Order entry is unavailable"
  | "Order entry is unavailable: {reason}"
  | "Other"
  | "PNG, SVG, CSV or the clipboard"
  | "Pane {number}"
  | "Paste"
  | "Pick an indicator from the legend first"
  | "Pin price per bar"
  | "Pin to rail"
  | "Pinned. Right-click to unpin"
  | "Plot"
  | "Price"
  | "Price chart"
  | "Price {price}"
  | "Price {price} to {upper}"
  | "Properties"
  | "Properties of the selection..."
  | "Properties..."
  | "Ratio"
  | "Redo"
  | "Refreshing {symbol} {interval}"
  | "Remove"
  | "Remove all drawings ({count})"
  | "Remove level"
  | "Remove {name}"
  | "Removed {count} drawing"
  | "Removed {count} drawings"
  | "Reset"
  | "Restore defaults"
  | "Restore this tab"
  | "Retry"
  | "Retry chart data"
  | "Retry older history"
  | "Retry {name}"
  | "Right-click to remove all"
  | "Save"
  | "Saved a PNG of the chart"
  | "Saved an SVG of the chart"
  | "Scale"
  | "Search indicators"
  | "Search name, type or pane"
  | "Search objects"
  | "Searching"
  | "Select a drawing first"
  | "Select a drawing with levels first"
  | "Select a text drawing first"
  | "Select all ({count})"
  | "Select an input plot on the drawing pane"
  | "Select one first. Right-click to remove all"
  | "Select {name}"
  | "Selected"
  | "Selected drawing"
  | "Sell limit at {price}"
  | "Sell market"
  | "Sell stop at {price}"
  | "Send to back"
  | "Settings"
  | "Settings for {name}"
  | "Settings..."
  | "Show"
  | "Show drawing"
  | "Show labels"
  | "Show {name}"
  | "Source"
  | "Stay: {mode}"
  | "Stays selected, so the eye brings it back"
  | "Studies"
  | "Study"
  | "Study instance is unavailable"
  | "Study plot is unavailable"
  | "Style"
  | "Switch to the dark theme"
  | "Switch to the light theme"
  | "Symbol"
  | "Symbol search results"
  | "Symbols"
  | "Text"
  | "That indicator is no longer on the chart"
  | "That side is already in use"
  | "That text is off the chart"
  | "The anchor changes only while the drawing's pane is on screen"
  | "The canvas produced no image"
  | "The chart changed; reopen Capture for its current source"
  | "The chart changed; reopen the menu before placing an order"
  | "The chart layout could not be saved"
  | "The chart layout could not be saved: {error}"
  | "The current plot value is unavailable. The alert waits for observed values."
  | "The indicator picker is not in this build"
  | "The instrument context changed. Reopen the editor for the intended instrument."
  | "The saved layout could not be restored: {error}"
  | "The scale could not be moved"
  | "The settings dialog is not in this build"
  | "The study settings could not be applied"
  | "Theme"
  | "These drawings share no settings."
  | "This alert was removed"
  | "This runtime cannot save files"
  | "Tools"
  | "Tools stay armed after each drawing"
  | "Trade"
  | "Triggered"
  | "Unavailable candle condition"
  | "Unavailable drawing"
  | "Unavailable study"
  | "Unavailable study output: {instanceId} / {plotKey}"
  | "Undo"
  | "Unlock"
  | "Unlock drawing"
  | "Unlock {name}"
  | "Unlocked"
  | "Unpin from rail"
  | "Unsupported"
  | "Visible"
  | "Vol"
  | "Wait for this chart to finish loading its data"
  | "locked"
  | "needs https or localhost"
  | "nothing measured"
  | "nothing on this side"
  | "object"
  | "off"
  | "on"
  | "on chart"
  | "on chart x{count}"
  | "one instance on the chart"
  | "other side taken"
  | "paste it anywhere"
  | "read-only"
  | "text stays text"
  | "{count} alert"
  | "{count} alerts"
  | "{count} bars"
  | "{count} chart shortcut struck through: the same chord arms a drawing tool here and takes precedence."
  | "{count} chart shortcuts struck through: the same chord arms a drawing tool here and takes precedence."
  | "{count} drawings"
  | "{count} instances on the chart"
  | "{count} objects"
  | "{group}: chevron for the rest"
  | "{group}: chevron for the rest. Double-click keeps it armed"
  | "{name} / {plot}: {value}"
  | "{name} / {plot}: {value} to {upper}"
  | "{name} has nothing to configure"
  | "{name} settings"
  | "{name} settings..."
  | "{name} stays armed until Escape"
  | "{seconds}s cooldown"
  | "{shown} of {count} objects";

/** Schema keys name descriptor metadata, never saved user values. */
export type WidgetMessageKey = WidgetBuiltinMessage | `schema.${string}`;
export type WidgetMessageValues = Readonly<Record<string, string | number>>;

/** A synchronous host catalog. Missing entries return undefined or null. */
export type WidgetTranslator = (key: WidgetMessageKey, fallback: string, values: WidgetMessageValues) => string | null | undefined;

export interface WidgetTranslationOptions {
  /** Translates widget-owned text. Omit to preserve English rendering. */
  translate?: WidgetTranslator;
}

/** Required interpolation names are inferred from the English source message. */
export type WidgetMessageParameters<Message extends string> = Message extends `${string}{${infer Name}}${infer Rest}`
  ? Readonly<Record<Name, string | number> & WidgetMessageParameters<Rest>> : Readonly<Record<never, never>>;

const EMPTY: WidgetMessageValues = Object.freeze({});
const PARAMETER = /\{([A-Za-z][A-Za-z0-9_]*)\}/g;

/** Resolve a message, then interpolate literal values once. Output is plain text. */
export function widgetText<K extends WidgetBuiltinMessage>(context: WidgetTranslationOptions, key: K,
  ...args: [keyof WidgetMessageParameters<K>] extends [never] ? [values?: WidgetMessageValues] : [values: WidgetMessageParameters<K>]): string;
export function widgetText(context: WidgetTranslationOptions, key: `schema.${string}`, values: WidgetMessageValues, fallback: string): string;
export function widgetText(context: WidgetTranslationOptions, key: WidgetMessageKey, values: WidgetMessageValues = EMPTY, fallback: string = key): string {
  let message = fallback;
  if (context.translate !== undefined) {
    try {
      const translated = context.translate(key, fallback, Object.freeze({ ...values }));
      if (typeof translated === 'string' && translated.trim() !== '') {
        const required = new Set(Array.from(fallback.matchAll(PARAMETER), match => match[1]));
        const supplied = new Set(Array.from(translated.matchAll(PARAMETER), match => match[1]));
        if (required.size === supplied.size && [...required].every(name => supplied.has(name))) message = translated;
      }
    } catch { /* A missing host catalog must not disable a chart control. */ }
  }
  return message.replace(PARAMETER, (token, name: string) => Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : token);
}
