export default {
  '-- intro': { type: 'separator', title: 'Introduction' },
  'getting-started': 'Getting Started',
  'migrating-to-2': 'Migrating to 2.0',
  cdn: 'Use from a CDN',
  'core-concepts': 'Core Concepts',
  architecture: 'Architecture',
  widget: 'The Widget Tier',
  frameworks: 'Framework Integration',

  '-- guides': { type: 'separator', title: 'Guides' },
  'chart-types': 'Chart Types',
  'series-and-styling': 'Series & Styling',
  rendering: 'Render Backends & SVG Export',
  'timeframes-and-tick-charts': 'Timeframes & Tick Charts',
  timezones: 'Timezones',
  'scales-and-panes': 'Scales & Panes',
  'price-levels': 'Price Levels & Axis Chrome',
  'symbol-comparison': 'Symbol Comparison',
  'chart-linking': 'Chart Linking',
  themes: 'Theming & Chart Options',
  'settings-and-menus': 'Settings & Menus',
  indicators: 'Indicators',
  transforms: 'Transforms',
  'primitives-and-plugins': 'Primitives & Plugins',
  'drawing-tools': 'Drawing Tools',
  'drawing-clipboard': 'Drawing Clipboard',
  'profiles-and-orderflow': 'Profiles & Order Flow',
  'market-profile': 'Market Profile (TPO)',
  'volume-profile': 'Volume Profile',
  'market-replay': 'Market Replay',
  'crosshair-and-legend': 'Crosshair & Legend',
  state: 'Chart State',
  interactions: 'Interactions & A11y',
  'keyboard-shortcuts': 'Keyboard Shortcuts',
  events: 'Events',
  mobile: 'Mobile & Touch',

  '-- trading': { type: 'separator', title: 'Trading' },
  'trading-api': 'Trading API',
  trading: 'Order Engine & Ladder',

  '-- data': { type: 'separator', title: 'Data & Feeds' },
  'data-loading': 'Data Loading',
  'live-data': 'Live Data (OpenAlgo)',
  'performance-and-operations': 'Performance & Operations',
  'data-feeds': 'Custom Data Feeds',
  'bar-cache': 'Bar Cache',
  'custom-intervals': 'Custom Intervals',

  '-- reference': { type: 'separator', title: 'Reference' },
  types: 'Types Reference',
  constants: 'Constants & Helpers',
  glossary: 'Glossary',
  'release-notes': 'Release Notes',
};
